# Generated by Django 4.0 on 2023-06-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcontact',
            name='phone2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='addcontact',
            name='phone1',
            field=models.CharField(max_length=50),
        ),
    ]
